Error fallo

diff --git a/.github/workflows/main_workflow.yml b/.github/workflows/main_workflow.yml
--- a/.github/workflows/main_workflow.yml
+++ b/.github/workflows/main_workflow.yml
@@ -39,6 +39,12 @@ jobs:
           run: npm install Jest --legacy-peer-deps
         - name: Run Jest Test
           run: npm run test
+          id: jest
+          continue-on-error: true
+        - name: Fails
+          if: steps.jest.outcome != 'success'
+          run: echo "Se ha producido un error" && exit 1
+          
     environment_test_execution:
       runs-on: ubuntu-latest
       needs: [linter-execution, test-execution]
